import os
import logging
import re

logger = logging.getLogger(__name__)

def process_subtitle(input_file, output_file=None):
    """
    Process ASS subtitle file:
    1. Replace Script Info and Style sections with template
    2. Remove dialogs before episode number
    3. Maintain position tags for all dialogs
    """
    try:
        if output_file is None:
            output_file = f"processed_{os.path.basename(input_file)}"
            
        # Template for Script Info and Styles
        template = '''[Script Info]
; Script generated by FFmpeg/Lavc58.35.100
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Oath-Bold,20,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n'''

        with open(input_file, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        # Find dialogs and process them
        processed_dialogs = []
        episode_found = False
        episode_line = None
        
        for line in lines:
            if line.startswith('Dialogue:'):
                # Check if this is the episode line
                if 'Episode' in line or 'episode' in line:
                    episode_found = True
                    episode_line = line
                    continue
                
                # Only keep dialogs after finding the episode line
                if episode_found:
                    parts = line.split(',', 9)
                    if len(parts) > 9:
                        text = parts[9].strip()
                        # Remove all existing tags except pos
                        text = re.sub(r'{[^{}]*}', '', text)
                        # Add position tag
                        text = f"{{\\pos(193,265)}}{text}"
                        parts[9] = text + '\n'
                        processed_dialogs.append(','.join(parts))

        # Write the processed file
        with open(output_file, 'w', encoding='utf-8') as f:
            # Write template
            f.write(template)
            
            # Write episode line first if found
            if episode_line:
                parts = episode_line.split(',', 9)
                if len(parts) > 9:
                    text = parts[9].strip()
                    # Remove all tags and add episode formatting
                    text = re.sub(r'{[^{}]*}', '', text)
                    # Format episode text
                    if 'Episode' in text:
                        text = text.replace('Episode:', 'Episode:').strip()
                        text = f"{{\\pos(193,265)}}{text} [HeavenlySubs]\n"
                    parts[9] = text
                    f.write(','.join(parts))
            
            # Write remaining dialogs
            for dialog in processed_dialogs:
                f.write(dialog)

        logger.info(f"Successfully processed subtitle: {output_file}")
        return True, output_file
        
    except Exception as e:
        logger.error(f"Error processing subtitle: {e}")
        return False, str(e)